GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "SDASD",
    "author": "this guy",
    "url": "/asdasd/asdasd",
    "likes": 2
}