GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "author": "this guy",
    "likes": 2
}

###

PUT http://localhost:3001/api/blogs/5f33cf63c0f8052b468d4839
content-type: application/json

{
    "title": "Changed title",
    "url" : "/url/to/new",
    "author": "Arbnor Lumezi",
    "likes": 100
}

###

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer xxx

{
    "title": "Authorized title",
    "url" : "/url/to/authorized",
    "author": "Arbnor Lumezi",
    "likes": 100
}

###

DELETE  http://localhost:3001/api/blogs/5f6a493775505b6a083d00dd
Authorization: Bearer 

###

POST  http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"Arbnor",
    "name" : "Arbnor Lumezi",
    "password" : "asda123123sd"
}

###

GET   http://localhost:3001/api/users

###

GET   http://localhost:3001/api/users/5f627ee3f622cf2ad75134a3

###

POST   http://localhost:3001/api/login
Content-Type: application/json

{
    "username" : "Arbnor",
    "password" : "asda123123sd"
}
